name: Run Tests on Multiple OS

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  schedule:
    - cron: '59 21 * * 0'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        java: [17]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Build project without tests
        run: mvn clean install -DskipTests=true

      - name: Run tests
        run: mvn test

      - name: Archive Cucumber reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports-${{ matrix.os }}
          path: target/cucumber-reports/

      # - name: Archive test reports (Surefire)
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: surefire-reports-${{ matrix.os }}
      #     path: target/surefire-reports/
